### ISSUE TITLE
how to support ecdsa address and output script

### ISSUE THREAD

**Issue by benjamintshi** [aspectron/kaspa-core-lib#5]
network: 'mainnet',
address: 'kaspa:qyph47ecjvpkkqw5x3khqxzh7u0w9cqqzxmq0z9vtzt3fprmn758ujs8zwlaws0'  --> this is ecdsa type adress

const { address } = params;
    try {
        kaspacore.Address(address);
        return true;
    }
    catch (error) {
        console.error(error);
        return false;
}

Invalid Argument: Invalid hash size:kaspa:qyph47ecjvpkkqw5x3khqxzh7u0w9cqqzxmq0z9vtzt3fprmn758ujs8zwlaws0

**--> need build ecdsa output script**
 
tx.addOutput(new kaspacore.Transaction.Output({
    script: new kaspacore.Script(new kaspacore.Address(output.address)).toBuffer().toString('hex'),
     satoshis: amount,
}));

**Comment by coderofstuff** [comment]
This sample code works:

```
const Address = require('./lib/address');
const Script = require('./lib/script');

const addr = new Address('kaspa:qyph47ecjvpkkqw5x3khqxzh7u0w9cqqzxmq0z9vtzt3fprmn758ujs8zwlaws0');
console.info(addr);

console.info(addr.hashBuffer.toString('hex'))

const pubkey = addr.hashBuffer.toString('hex');
console.info(pubkey);
console.info(new Script(addr).toHex());
```

So, instead of:
```
script: new kaspacore.Script(new kaspacore.Address(output.address)).toBuffer().toString('hex'),
```

try
```
script: new kaspacore.Script(new kaspacore.Address(output.address)).toHex(),
```
